# https://appdividend.com/2021/06/21/how-to-read-file-into-list-in-python/
# https://www.w3schools.com/python/python_lists_loop.asp
# https://stackoverflow.com/questions/49777888/pass-python-variable-inside-command-with-paramiko
# Allworx CLI: https://community.fortinet.com/t5/FortiGate/Technical-Tip-Virtual-IP-VIP-port-forwarding-configuration/ta-p/198143
# SUBLIME:
# https://stackoverflow.com/questions/39556514/sublime-text-3-how-to-edit-multiple-lines
# https://gist.github.com/martincr/34f4fa08f6924512487d5b683c4fe800
import paramiko
import cmd
import time
import sys

connectionip = input('IP to SSH to:\n')
fortiusername = input('Fortigate Username:\n')
fortipassword = input('Fortigate Password:\n')
allworxpublicvip = input('Allworx Public IP:\n')
allworxprivateip = input('Allworx Private IP:\n')
localnetworkinterface = input('Local Network Interface Name:\n')

buff = ''
resp = ''

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(connectionip, username=fortiusername, password=fortipassword)
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
chan = ssh.invoke_shell()

# turn off paging
chan.send('terminal length 0\n')
time.sleep(1)
resp = chan.recv(9999)
output = resp.decode('ascii').split(',')
#print (''.join(output))


# Display output of first command
chan.send('config firewall vip')
chan.send('\n')
# Allworx_IP 5060_tcp
chan.send('edit "Allworx_IP 5060_tcp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set extport 5060')
chan.send('\n')
chan.send('set mappedport 5060')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 5060_udp
chan.send('edit "Allworx_IP 5060_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set protocol udp')
chan.send('\n')
chan.send('set extport 5060')
chan.send('\n')
chan.send('set mappedport 5060')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 15000-15511_udp
chan.send('edit "Allworx_IP 15000-15511_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set protocol udp')
chan.send('\n')
chan.send('set extport 15000-15511')
chan.send('\n')
chan.send('set mappedport 15000-15511')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 8443_udp
chan.send('edit "Allworx_IP 8443_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set extport 8443')
chan.send('\n')
chan.send('set mappedport 8443')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 8081_udp
chan.send('edit "Allworx_IP 8081_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set extport 8081')
chan.send('\n')
chan.send('set mappedport 8081')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 2088_udp
chan.send('edit "Allworx_IP 2088_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set protocol udp')
chan.send('\n')
chan.send('set extport 2088')
chan.send('\n')
chan.send('set mappedport 2088')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 443_udp
chan.send('edit "Allworx_IP 443_udp"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set extport 443')
chan.send('\n')
chan.send('set mappedport 443')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_SMTP
chan.send('edit "Allworx_SMTP"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "any"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set extport 25')
chan.send('\n')
chan.send('set mappedport 25')
chan.send('\n')
chan.send('next')
chan.send('\n')

# Allworx_IP 16384-32767
chan.send('edit "Allworx_IP 16384-32767"')
chan.send('\n')
chan.send('set extip '+ allworxpublicvip)
chan.send('\n')
chan.send('set mappedip "' + allworxprivateip  + '"')
chan.send('\n')
chan.send('set extintf "wan1"')
chan.send('\n')
chan.send('set portforward enable')
chan.send('\n')
chan.send('set protocol udp')
chan.send('\n')
chan.send('set extport 16384-32767')
chan.send('\n')
chan.send('set mappedport 16384-32767')
chan.send('\n')
chan.send('next')
chan.send('\n')
chan.send('end')
chan.send('\n')


# Create Virtual IP Group
chan.send('config firewall vipgrp')
chan.send('\n')
chan.send('edit Allworx')
chan.send('\n')
chan.send('set interface wan1')
chan.send('\n')
chan.send('set member Allworx_IP\ 5060_tcp Allworx_IP\ 5060_udp Allworx_IP\ 16384-32767 Allworx_SMTP Allworx_IP\ 443_udp Allworx_IP\ 2088_udp Allworx_IP\ 8081_udp Allworx_IP\ 8443_udp Allworx_IP\ 15000-15511_udp')
chan.send('\n')
chan.send('next')
chan.send('\n')
chan.send('end')
chan.send('\n')

# Create Allworx Policy
chan.send('config firewall policy')
chan.send('\n')
chan.send('edit 90')
chan.send('\n')
chan.send('set name "Allworx"')
chan.send('\n')
chan.send('set srcintf "wan1"')
chan.send('\n')
chan.send('set dstintf "' + localnetworkinterface  + '"')
chan.send('\n')
chan.send('set action accept')
chan.send('\n')
chan.send('set srcaddr "all"')
chan.send('\n')
chan.send('set dstaddr "Allworx"')
chan.send('\n')
chan.send('set schedule "always"')
chan.send('\n')
chan.send('set service "ALL"')
chan.send('\n')
chan.send('next')
chan.send('\n')
chan.send('end')
chan.send('\n')
time.sleep(1)
resp = chan.recv(9999)
output = resp.decode('ascii').split(',')
print (''.join(output))



ssh.close() 
